version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/${UI_VER}
    ports:
      - ${PORT}
    networks:
      - front_net
      - back_net
  post:
    build: ./post-py
    image: ${USERNAME}/${POST_VER}
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/${COMMENT_VER}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
